title: Opencv Tutorial
theme: jekyll-theme-cayman

description: OpenCV Tutorial
author:
  name: Hamid Farzaneh
  email: hamidfarzaneh75@gmail.com
  github: hamidfarzaneh 
  bio: trying to be a programmer
  linkedin: hamid farzaneh 