# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: dbyll
google_analytics: dbyll
title: OpenCV Tutorial

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: OpenCV Tutorial 

description: OpenCV Tutorial
author:
  name: Hamid Farzaneh
  email: hamidfarzaneh75@gmail.com
  github: hamidfarzaneh 
  bio: trying to be a programmer
  linkedin: hamid farzaneh 

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
